FROM balenalib/raspberrypi3-python:3.7.4-buster
RUN apt update && apt install wireless-tools python3 python3-setuptools python3-pip python3-dev libraspberrypi-bin iputils-ping && usermod -a -G video root
RUN pip3 install wheel
COPY requirements.txt smartcarsocket.py /
RUN pip3 install -r /requirements.txt
ARG commit
RUN echo -n $commit > /commit.txt