FROM balenalib/raspberrypi3-golang:1.11.13 as firststage
WORKDIR /smartcar
ADD . .
RUN go build -o controller .
FROM balenalib/raspberrypi3:buster-20200207
WORKDIR /smartcar
COPY --from=firststage /smartcar/controller .
CMD ["./controller"]