FROM jrcichra/smartcar_python_base_rpi
ARG commit
EXPOSE 8080
COPY requirements.txt /
RUN pip3 install -r /requirements.txt && apt install -y openssh-client sshpass
COPY . /
RUN echo -n $commit > /commit.txt
CMD python3 -u transfer.py