ARG VERSION=latest
FROM jrcichra/smartcar_python_base_rpi:${VERSION}
RUN apt-get update && apt-get install -y expect openssh-client sshpass && rm -rf /var/lib/apt/lists/*
COPY requirements.txt /
RUN pip3 install -r /requirements.txt
COPY . /
CMD python3 -u transfer.py