ARG VERSION=latest
FROM jrcichra/smartcar_python_base_rpi:${VERSION}
RUN install_packages python3-rpi.gpio
COPY requirements.txt /
RUN pip3 install -r /requirements.txt 
COPY . /
CMD python3 -u gpio.py
