FROM jrcichra/smartcar_python_base_rpi
ARG commit
EXPOSE 8080
COPY . /
RUN apt install -y python3-rpi.gpio
RUN pip3 install -r /requirements.txt && echo -n $commit > /commit.txt
CMD python3 -u gpio.py